apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-hello-world
  labels:
    app: hello-world
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    app: hello-world
    release: {{ .Release.Name }}